version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  gomonolith:
    build:
      context: .
    ports:
      - 3001:3001
    networks:
      - elasticsearch
    depends_on:
      - elasticsearch

networks:
  elasticsearch: